version: '3'

services:
  web:
    build:
      context: web
      dockerfile: ./Dockerfile
    env_file:
      - ./web/.env
    ports:
      - 3000:3000
      - 4173:4173
    volumes:
      - ./web:/app:z

  server:
    build:
      context: server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8000:8000
    volumes:
      - ./server:/app:z
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
