# Generated by Django 4.1.3 on 2022-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_task_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectusers',
            options={'verbose_name_plural': 'Project Users'},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name_plural': 'Task Lists'},
        ),
    ]
