# Generated by Django 4.1.3 on 2023-10-22 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_fileexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileexport",
            name="email_sent_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 22, 7, 30, 55, 170509, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
            preserve_default=False,
        ),
    ]
