# Generated by Django 4.1.3 on 2023-10-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_fileexport_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileexport',
            name='email_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
