# Generated by Django 4.1.3 on 2022-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationusers',
            options={'verbose_name_plural': 'Organization Users'},
        ),
    ]
