# Generated by Django 4.1.3 on 2022-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='invitation_code',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
