# Generated by Django 4.1.3 on 2023-08-26 10:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_organizationinvitation_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.profile_pic_path),
        ),
    ]
