"""add unique hash to user

Revision ID: 096b3f0f0328
Revises: c17130c9f8c4
Create Date: 2022-10-13 17:20:56.419787

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '096b3f0f0328'
down_revision = 'c17130c9f8c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash')
    # ### end Alembic commands ###
