"""update user model

Revision ID: 0eff92d758a8
Revises: decdb17e919d
Create Date: 2022-11-05 13:23:34.482405

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0eff92d758a8'
down_revision = 'decdb17e919d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inviteduser_email_invited_to_key', 'inviteduser', type_='unique')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint('inviteduser_email_invited_to_key', 'inviteduser', ['email', 'invited_to'])
    # ### end Alembic commands ###
