"""remove task status

Revision ID: 7b480c261978
Revises: f948da451a3f
Create Date: 2022-09-29 16:42:16.876824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b480c261978'
down_revision = 'f948da451a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', postgresql.ENUM('CREATED', 'COMPLETED', name='taskstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
