"""add task start/due dates

Revision ID: a09d070b1842
Revises: e7da999eeee0
Create Date: 2022-09-27 16:38:23.398938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a09d070b1842'
down_revision = 'e7da999eeee0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'start_date')
    # ### end Alembic commands ###
