"""add projects to organization

Revision ID: c770b7675e5a
Revises: 0eff92d758a8
Create Date: 2022-11-11 09:36:48.067326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlmodel import select

from apps.projects.models import Project
from apps.user.models import OrganizationRole


# revision identifiers, used by Alembic.
revision = "c770b7675e5a"
down_revision = "0eff92d758a8"
branch_labels = None
depends_on = None

connection = op.get_bind()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "project_organization_id_fkey",
        "project",
        "organization",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_organization_id_fkey", "project", type_="foreignkey")
    op.drop_column("project", "organization_id")
    # ### end Alembic commands ###
