"""add inviteduser data

Revision ID: decdb17e919d
Revises: de0fe4a639f7
Create Date: 2022-11-03 12:51:45.677853

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "decdb17e919d"
down_revision = "de0fe4a639f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inviteduser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "invite_code", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column("invited_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("invited_by", sa.Integer(), nullable=False),
        sa.Column("invited_to", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_to"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "invited_to"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inviteduser")
    # ### end Alembic commands ###
