"""add tasks to projects

Revision ID: f948da451a3f
Revises: 19ce35344d23
Create Date: 2022-09-29 07:15:30.568820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f948da451a3f'
down_revision = '19ce35344d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('task', 'tasklist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'tasklist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
