name: Build React Application

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd web
      - run: npm ci
      - run: npm run build
